collections:
- name: community.general
  type: galaxy
  version: 4.0.2

- name: community.network
  type: galaxy
  version: 5.0.2

- name: community.routeros
  type: galaxy
  version: 2.13.0
  
- name: openstack.cloud
  type: galaxy
  version: 2.2.0
