collections:
- name: community.general
  type: galaxy
  version: 4.0.2

- name: community.network
  type: galaxy
  version: 3.0.0

- name: community.routeros
  type: galaxy
  version: 2.0.0
  
- name: openstack.cloud
  type: galaxy
  version: 2.1.0
