---
- hosts: localhost
  gather_facts: no
  tasks:
     - os_server_info:
         filters:
           name: "{{ username }}chr1"
       register: chr_server
     - ansible.builtin.debug:
          msg: "{{ hostvars['localhost'] }}"
     - set_fact:
          mikrotik_ipv4: "{{ chr_server.openstack_servers | json_query('[].public_v4') | join('\n') }}"
          mikrotik_ipv6: "{{ chr_server.openstack_servers | json_query('[].public_v6') | join('\n') }}"
          mikrotik_id: "{{ chr_server.openstack_servers | json_query('[].id') | join('\n') }}"
     - ansible.builtin.debug:
          msg: mikrotik_ipv4 {{ mikrotik_ipv4 }}
     - os_port_info:
         filters:
           device_id: "{{ mikrotik_id }}"
       register: chr_port
     - set_fact:
          query_gw_v4: "[?ip_address=='{{ mikrotik_ipv4 }}'].subnet_id"
          query_gw_v6: "[?ip_address=='{{ mikrotik_ipv6 }}'].subnet_id"
          subnet_id_v4: "{{ chr_port.openstack_ports | json_query('[].fixed_ips[]') }}"
          subnet_id_v6: "{{ chr_port.openstack_ports | json_query('[].fixed_ips[]') }}"
     - set_fact:
          subnet_id_v4: "{{ subnet_id_v4 | json_query(query_gw_v4) | join('\n') }}"
          subnet_id_v6: "{{ subnet_id_v6 | json_query(query_gw_v6) | join('\n') }}"
     - os_subnets_info:
         filters:
           id: "{{ subnet_id_v4 }}"
       register: chr_subnet
     - set_fact:
          gw_ipv4: "{{ chr_subnet.openstack_subnets | json_query('[].gateway_ip') | join('\n') }}"
          cidr_ipv4: "{{ chr_subnet.openstack_subnets | json_query('[].cidr') | join('\n') }}"
     - os_subnets_info:
         filters:
           id: "{{ subnet_id_v6 }}"
       register: chr_subnet_v6
     - set_fact:
          gw_ipv6: "{{ chr_subnet_v6.openstack_subnets | json_query('[].gateway_ip') | join('\n') }}"
          cidr_ipv6: "{{ chr_subnet_v6.openstack_subnets | json_query('[].cidr') | join('\n') }}"

- hosts: "{{ username }}chr1"
  gather_facts: no
  vars:
    ansible_connection: network_cli
    ansible_network_os: routeros
    ansible_user: admin
  pre_tasks:
     - set_fact:
          gw_ipv4: "{{ hostvars['localhost']['gw_ipv4'] }}"
          mikrotik_ipv4: "{{ hostvars['localhost']['mikrotik_ipv4'] }}"
          gw_ipv6: "{{ hostvars['localhost']['gw_ipv6'] }}"
          mikrotik_ipv6: "{{ hostvars['localhost']['mikrotik_ipv6'] }}"
  roles:
    - hoplacloud.mikrotik
